# See LICENSE for license details.

.PHONY: force_rule_to_run
force_rule_to_run:
	echo "Forcing downstream rule to run"

CHIPYARD_STAGING_DIR := $(chipyard_dir)/sims/firesim-staging

# can't symlink the top-level since target/ generated by sbt will be shared amongst chipyard/firesim causing errors
# TODO: AJG: unsure if this updates timestamps...
# TODO: AJG: also unsure how this interacts with make requirements...
.PHONY: symlink_firesim_files
symlink_firesim_files:
	mkdir -p $(firesim_base_dir)/midas/src/main/scala/bridge-interfaces
	ln -sf $(chipyard_dir)/generators/firechip/bridge-interfaces/src \
		$(firesim_base_dir)/midas/src/main/scala/bridge-interfaces/.
	mkdir -p $(firesim_base_dir)/midas/src/main/scala/firesim-only
	ln -sf $(chipyard_dir)/generators/firechip/firesim-only/src \
		$(firesim_base_dir)/midas/src/main/scala/firesim-only/.

# this rule always is run, but may not update the timestamp of the targets (depending on what the Chipyard make does).
# if that is the case (Chipyard make doesn't update it's outputs), then downstream rules *should* be skipped.
# all other chipyard collateral is located in chipyard's generated sources area.
$(FIRRTL_FILE) $(ANNO_FILE) &: SHELL := /usr/bin/env bash # needed for running source in recipe
$(FIRRTL_FILE) $(ANNO_FILE) &: force_rule_to_run symlink_firesim_files
	@mkdir -p $(@D)
	source $(chipyard_dir)/env.sh && \
		make -C $(CHIPYARD_STAGING_DIR) \
			SBT_PROJECT=$(TARGET_SBT_PROJECT) \
			MODEL=$(DESIGN) \
			MODEL_PACKAGE=$(DESIGN_PACKAGE) \
			VLOG_MODEL=$(DESIGN) \
			CONFIG=$(TARGET_CONFIG) \
			CONFIG_PACKAGE=$(TARGET_CONFIG_PACKAGE) \
			GENERATOR_PACKAGE=chipyard \
			TB=unused \
			TOP=unused
	# $(long_name) must be same as Chipyard
	# only copies if updated
	rsync -pthrvz $(CHIPYARD_STAGING_DIR)/generated-src/$(long_name)/$(long_name).fir $(FIRRTL_FILE)
	rsync -pthrvz $(CHIPYARD_STAGING_DIR)/generated-src/$(long_name)/$(long_name).anno.json $(ANNO_FILE)
